version: '2.1'

# ACTUAL CONFIGURATION
services:
  # DATABASE CONFIGURATION
  psql:
    command: postgres -c logging_collector=on
      -c log_min_duration_statement=0
      -c log_directory='/var/log/postgresql'
      -c log_min_messages='WARNING'
      -c log_rotation_age='1d'
      -c log_rotation_size='1GB'
    container_name: db_postgresql
    hostname: psql
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'qusUt1i9obru4ISTUG2f'
    ports:
    - "5432:5432"
    volumes:
    - psql:/var/log/postgresql
    networks:
    - elk
    - api

  elasticsearch:
    container_name: elk_elasticsearch
    build:
      context: config/docker/elasticsearch/
    volumes:
    - ./config/docker/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
    - "9200:9200"
    - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
    - elk

  kibana:
    container_name: elk_kibana
    build:
      context: config/docker/kibana/
    volumes:
    - ./config/docker/kibana/config/:/usr/share/kibana/config:ro
    ports:
    - "5601:5601"
    networks:
    - elk
    depends_on:
    - elasticsearch

  filebeat:
    restart: always
    container_name: elk_filebeat
    user: root
    build:
      context: config/docker/filebeat/
    volumes:
      - ./config/docker/filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - psql:/var/log/postgresql
    ports:
    - "5044:5044"
    environment:
      - ELASTIC_SEARCH_HOST=elasticsearch:9200
      - LOGS_ROUTE=/pierpontglobal-api/logs/
    networks:
    - elk

  redis:
    user: root
    restart: always
    command: '--logfile /var/log/redis/redis-server.log'
    container_name: redis
    build:
      context: config/docker/redis
    logging:
      driver: "json-file"
    volumes:
    - redis:/var/log/redis
    ports:
    - '6379:6379'
    networks:
    - api

  rails:
    restart: always
    user: root
    container_name: pierpont_api
    build: .
    command: bin/start_rails_docker
    volumes:
    - .:/pierpontglobal-api
    environment:
    - DB_HOST=psql
    - DB_PASSWORD=qusUt1i9obru4ISTUG2f
    - DB_USER=postgres
    - JOB_WORKER_URL=redis://redis:6379/0
    - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
    - "3000:3000"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
    - api
    - elk

networks:
  elk:
    driver: bridge
  api:
    driver: bridge

volumes:
  psql:
    driver: local
  nginx:
    driver: local
  redis:
    driver: local