version: '3'

volumes:
  esdata1:
    driver: local

networks:
  esnet:

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
    container_name: elasticsearch
    environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - esdata1:/usr/share/elasticsearch/data
    ports:
    - "9200:9200"
    networks:
    - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.1
    environment:
      - ELASTICSEARCH_URL="http://172.19.0.1:9200"
    ports:
    - "5601:5601"
    depends_on:
      - elasticsearch
  logstash:
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    image: logstash:latest
    ports:
    - '5000:5000'
    depends_on:
    - elasticsearch
    volumes:
    - ./config/docker-logstash.conf:/etc/logstash/conf.d/logstash.conf
  nginx:
    command: /docker/docker-start-nginx.sh
    depends_on:
    - rails
    environment:
    - WORKER_PROCESSES=2
    image: nginx:latest
    ports:
    - '80:80'
    - '443:443'
    volumes:
    - ./bin/docker-start-nginx.sh:/docker/docker-start-nginx.sh
    - ./config/docker-nginx.conf.template:/docker/nginx.conf.template
    - ./config/docker-nginx.rails.conf:/etc/nginx/conf.d/rails.conf
  rails:
    build: .
    command: bin/docker-start-rails.sh
    volumes:
    - .:/pierpontglobal-api
    environment:
      - DB_HOST='172.18.0.1'
      - LOGSTASH_HOST='172.18.0.1'
    ports:
    - "3000:3000"