version: '2'
# TESTING 1
services:
  # DATABASE CONFIGURATION
  psql:
    command: postgres -c logging_collector=on
            -c log_min_duration_statement=0 
            -c log_directory='/var/log/postgresql' 
            -c log_min_messages='WARNING' 
            -c log_rotation_age='1d' 
            -c log_rotation_size='1GB'
    container_name: db_postgresql
    hostname: psql
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'qusUt1i9obru4ISTUG2f'
    ports:
    - "5432:5432"
    volumes:
      - psql:/var/log/postgresql
    networks:
      - elk
      - api

  elasticsearch:
    container_name: elk_elasticsearch
    build:
      context: config/docker/elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./config/docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    container_name: elk_logstash
    build:
      context: config/docker/logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./config/docker/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./config/docker/logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
      - api
    depends_on:
      - elasticsearch

  kibana:
    container_name: elk_kibana
    build:
      context: config/docker/kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./config/docker/kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  filebeat:
    restart: always
    container_name: elk_filebeat
    user: root
    build:
      context: config/docker/filebeat/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./config/docker/filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - psql:/var/log/postgresql
      - nginx:/var/log/nginx_pp
    ports:
      - "5044:5044"
    networks:
      - elk
    depends_on:
      - logstash

  redis:
    user: root
    restart: always
    command: '--logfile /var/log/redis/redis-server.log'
    container_name: redis
    build:
      context: config/docker/redis
    logging:
      driver: "json-file"
    volumes:
      - redis:/var/log/redis
    ports:
      - '6379'
    networks:
      - api

  rails:
    user: root
    container_name: pierpont_api
    build:
      context: .
    command: bin/start_rails_docker
    volumes:
    - .:/pierpontglobal-api
    environment:
      - DB_HOST=psql
      - JOB_WORKER_URL=redis://redis:6379/0
      - LOGSTASH_HOST=logstash
    ports:
    - "3000:3000"
    - "3001:3001"
    depends_on:
      - psql
    networks:
      - api

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./config/docker/web-conf/pierpont.conf:/etc/nginx/conf.d/default.conf
      - nginx:/var/log/nginx_pp
    networks:
      - web
      - api
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - rails
    restart: always

networks:
  elk:
    driver: bridge
  api:
    driver: bridge
  # If you would like to see the real client ip in the logs you need to change this to host instead of bridge
  # unless you are using MacOS Operating System since there is an active bug that prevents attaching to host.
  web:
    driver: bridge

volumes:
  psql:
    driver: local
  nginx:
    driver: local
  redis:
    driver: local