filebeat.prospectors:
  - input_type: log
    paths: ["${LOGS_ROUTE}/PierpontglobalApi.log"]
    json.keys_under_root: true
    fields:
      app_name: api
  - input_type: log
    paths: ["${LOGS_ROUTE}/PierpontglobalHealth.log"]
    json.keys_under_root: true
    fields:
      app_name: health

output.elasticsearch:
  hosts: ["${ELASTIC_SEARCH_HOST}"]
  template.name: pierpontapi_filebeat
  template.path: pierpontapi_filebeat.template.json
  index: "pierpont_%{[fields.app_name]}-%{+yyyy.MM.dd}"

setup.template:
  name: 'pierpont_'
  pattern: 'pierpont_*'
  enabled: false