# EMAILING CREDENTIALS
SENDGRID_API_KEY: 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
SENDGRID_API_KEY_SMTP: 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

# RAILS APP DEFAULT VALUES
CLIENT_TARGET: https://pierpontglobal.com
SOURCE_EMAIL: support@pierpontglobal.com
ADMIN_PASSWORD: WefrucaT7TAhl4weNUdr
ADMIN_CONTACT: "5555555555"
RAILS_LOG_TO_STDOUT: "true"
DEVISE_JWT_SECRET_KEY: aea35e8c8ca01e2afc0056286d9606e28d0e0e853358bed75552487d839d5a110828ebf6ff039892c2eb8071ea7743f6e7ffad732d7b96204abb4361e2c3aae7
#------------------------------------------#
DB_HOST: 0.0.0.0
DB_USER: postgres
DB_PASSWORD: qusUt1i9obru4ISTUG2f
JOB_WORKER_URL: redis://0.0.0.0:6379/0
ELASTICSEARCH_URL: http://0.0.0.0:9200

# MAXMIND CREDENTIALS
MAX_MIND_USER: "136313"
MAX_MIND_KEY: 7xJxUz4XO0rl

# MANHEIM CREDENTIALS
MANHEIM_API_KEY: a7y72qt9eeab9qme8z48vnz6

# SIDEKIQ  CREDENTIALS
PIERPONT_USER_SIDEKIQ: pierpont_admin
PIERPONT_PASS_SIDEKIQ: admin

# MESSAGING SERVICE CREDENTIALS
AUTHY_API_KEY: 1PvqM60vX93JTcYUw5jYxwkKpK238Zex
TWILIO_ACCOUNT_SID: ACe70e7799a0547395bd76df8b2664a89c
TWILIO_AUTH_TOKEN: 2e7420fc854158887c7e18ac1913a43d
TWILIO_NUMBER: "18325019168"

# AWS CREDENTIALS
AWS_REGION: us-east-1
AWS_ACCESS_KEY_ID: AKIAI566CCS72L4YKO4A
AWS_SECRET_ACCESS_KEY: 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

# ONE SIGNAL CREDENTIALS
ONESIGNAL_APP_ID: 5af646ab-8c73-474b-9ebf-f19036693a2b
ONESIGNAL_API_KEY: Y2YxMDhlN2YtZTY4OS00YmNiLWEyMTQtNTMyMDI5MGE2OTUw