SENDGRID_API_KEY: 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
SENDGRID_API_KEY_SMTP: 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
CLIENT_TARGET: https://pierpontglobal.com
SOURCE_EMAIL: support@pierpontglobal.com
ADMIN_PASSWORD: WefrucaT7TAhl4weNUdr
ADMIN_CONTACT: "5555555555" #Admincontact information
MAX_MIND_USER: "136313"
MAX_MIND_KEY: 7xJxUz4XO0rl
MANHEIM_API_KEY: a7y72qt9eeab9qme8z48vnz6
PIERPONT_USER_SIDEKIQ: pierpont_admin
PIERPONT_PASS_SIDEKIQ: admin
AUTHY_API_KEY: 1PvqM60vX93JTcYUw5jYxwkKpK238Zex
TWILIO_ACCOUNT_SID: ACe70e7799a0547395bd76df8b2664a89c
TWILIO_AUTH_TOKEN: 2e7420fc854158887c7e18ac1913a43d
TWILIO_NUMBER: "18325019168"
RAILS_LOG_TO_STDOUT: "true"

DB_HOST: 0.0.0.0
DB_USER: postgres
DB_PASSWORD: qusUt1i9obru4ISTUG2f
JOB_WORKER_URL: redis://redis:6379/0