development:
  adapter: redis
  url: redis://redis:6379

test:
  adapter: redis
  url: redis://redis:6379

production:
  adapter: redis
  url: <%= ENV.fetch("JOB_WORKER_URL") { "redis://redis:6379/1" } %>
  channel_prefix: pierpontglobal-api_production
