ScrapHeavyVehicles:
  every: ['1d', first_in: '60s']
  queue: scrap_heavy_vehicles
  class: ScrapHeavyVehicles
  description: "Get heavy vehicles from another source"
CarPulling:
  every: ['60m']
  queue: car_pulling
  class: PullCarsJob
  description: "Pull Cars from sources"