default: &default
  ScrabHeavyVehicles:
    every: ['60m', first_in: '60s']
    class: ScrabHeavyVehicles
    description: "Get heavy vehicles from another source"

development:
  <<: *default

staging:
  <<: *default

production:
  <<: *default