ScrapHeavyVehicles:
  every: ['1d', first_in: '60s']
  queue: default
  class: ScrapHeavyVehicles
  description: "Pull Cars from sources"
CarPulling:
  every: ['60m', first_in: '60s']
  queue: default
  class: PullCarsJob
  description: "Pull Cars from sources"